// Code generated by "stringer -type=MediaType"; DO NOT EDIT.

package media

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownMediaType-0]
	_ = x[Advertising-1]
	_ = x[Animation-2]
	_ = x[Anime-3]
	_ = x[ARG-4]
	_ = x[Audioplay-5]
	_ = x[Blog-6]
	_ = x[Comicbook-7]
	_ = x[Comicstrip-8]
	_ = x[Creator-9]
	_ = x[Fanfic-10]
	_ = x[Film-11]
	_ = x[Franchise-12]
	_ = x[Literature-13]
	_ = x[Magazine-14]
	_ = x[Manga-15]
	_ = x[Manhua-16]
	_ = x[Manhwa-17]
	_ = x[Music-18]
	_ = x[Pinball-19]
	_ = x[Podcast-20]
	_ = x[Radio-21]
	_ = x[Roleplay-22]
	_ = x[Script-23]
	_ = x[Series-24]
	_ = x[Tabletopgame-25]
	_ = x[Theatre-26]
	_ = x[Videogame-27]
	_ = x[Visualnovel-28]
	_ = x[WebAnimation-29]
	_ = x[Webcomic-30]
	_ = x[Website-31]
	_ = x[Webvideo-32]
	_ = x[Westernanimation-33]
	_ = x[Wrestling-34]
}

const _MediaType_name = "UnknownMediaTypeAdvertisingAnimationAnimeARGAudioplayBlogComicbookComicstripCreatorFanficFilmFranchiseLiteratureMagazineMangaManhuaManhwaMusicPinballPodcastRadioRoleplayScriptSeriesTabletopgameTheatreVideogameVisualnovelWebAnimationWebcomicWebsiteWebvideoWesternanimationWrestling"

var _MediaType_index = [...]uint16{0, 16, 27, 36, 41, 44, 53, 57, 66, 76, 83, 89, 93, 102, 112, 120, 125, 131, 137, 142, 149, 156, 161, 169, 175, 181, 193, 200, 209, 220, 232, 240, 247, 255, 271, 280}

func (i MediaType) String() string {
	if i < 0 || i >= MediaType(len(_MediaType_index)-1) {
		return "MediaType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MediaType_name[_MediaType_index[i]:_MediaType_index[i+1]]
}
