name: Build and Test Go project
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20'

            # Mask task runner needs Rust
            - name: Setup Rust
              uses: ATiltedTree/setup-rust@v1
              with:
                rust-version: stable

            - name: Install task runner
              run: cargo install mask
            
            - name: Build Go code
              run: mask build code

            - name: Test Go code
              run: mask test
