name: Check LaTeX grammar and spelling using Textidote
on: push
jobs:
  textidote_check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Lint spanish LaTeX document
        uses: ChiefGokhlayeh/textidote-action@v5.1.0
        id: lint
        env:
          ignore: sh:seclen,sh:stacked,sh:nobreak,sh:nonp
          removemacros: tableofcontents,listoffigures,listoftables,begin,centeroffset,oddsidemargin,evensidemargin,centering,bfseries,end,cleardoublepage,setlength,texttt,definecolor,titleformat,setcounter
          allowedwords: ../.github/workflows/allowed-words.txt
        with:
            root_file: proyecto.tex
            working_directory: docs
            args: --check es --ignore $ignore --remove otherlanguage --remove-macros $removemacros --dict $allowedwords
      - name: Lint english abstract
        uses: ChiefGokhlayeh/textidote-action@v5.1.0
        id: lintabstract
        env:
          ignore: sh:seclen,sh:stacked,sh:nobreak,sh:nonp,lt:es:DEL_LA
        with:
          root_file: english_abstract.tex
          working_directory: docs/prefacios
          args: --check en
      - name: Upload TeXtidote report
        uses: actions/upload-artifact@v2
        with:
            name: textidote_report
            path: docs/report.html
      - name: Throw error if linter warnings exist
        if: ${{ steps.lint.outputs.num_warnings != 0 && steps.lintabstract.outputs.num_warnings != 0 }}
        run: 'echo "::error file=main.tex::num_warnings: ${{ steps.lint.outputs.num_warnings }}"; exit 1;'
